name: Deploy Backend (production)

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://
    defaults:
      run:
        working-directory: ./packages/api
    steps:
      - uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Set tag
        run: echo "IMAGE_TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_URL: ${{ secrets.AWS_ECR_URL }}
        run: |
          docker build -t $ECR_URL:$IMAGE_TAG .
          docker tag $ECR_URL:$IMAGE_TAG $ECR_URL:latest
          docker push $ECR_URL:$IMAGE_TAG
          docker push $ECR_URL:latest
      - name: Install Selleo CLI
        uses: jaxxstorm/action-install-gh-release@v1.5.0
        with:
          repo: selleo/cli
          tag: v0.8.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: ECS Deployment
        env:
          AWS_REGION: eu-central-1
          ECS_CLUSTER: office-e17f626a
          ECS_SERVICE: api
          DOCKER_IMAGE: ${{ secrets.AWS_ECR_URL }}:${{ env.IMAGE_TAG }}
        run: selleo aws ecs deploy --region $AWS_REGION --cluster $ECS_CLUSTER --service $ECS_SERVICE --docker-image $DOCKER_IMAGE --one-off migration
      - name: ECS Run migrations
        env:
          AWS_REGION: eu-central-1
          ECS_CLUSTER: office-e17f626a
          ECS_SERVICE: api
        run: selleo aws ecs run --region $AWS_REGION --cluster $ECS_CLUSTER --service $ECS_SERVICE --one-off migration
